config/routes.rb
Rails.application.routes.draw do

  resources :events, only: [:index, :show]

  resources :registered_applications

  devise_for :users
  resources :users, only: [:show]

  namespace :api, defaults: { format: :json } do
    resources :events, only: [:create]
  end

  get "welcome/index"
  
  root to: 'welcome#index'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                        :integer          not null, primary key
#  name                      :string
#  registered_application_id :integer
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  user_id                   :integer
#

class Event < ActiveRecord::Base
  belongs_to :registered_application
  has_many :users, through: :registered_applications
  
  validates_presence_of :name
end

app/models/registered_application.rb
# == Schema Information
#
# Table name: registered_applications
#
#  id         :integer          not null, primary key
#  url        :string
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events, dependent: :destroy

  validates_presence_of :name
  validates_presence_of :url
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime
#  updated_at             :datetime
#  role                   :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :registered_applications, dependent: :destroy
  has_many :events, through: :registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    
    if registered_application.nil?
      render json: { error: "missing valid registered application URL" }, status: :unprocessable_entity
    else
      @event = registered_application.events.build( event_params )  
        if @event.save
          render json: @event, status: :created
        else
          render json: { error: "missing event name" }, status: :unprocessable_entity
        end
    end
  end
  
  private

  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
 
  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]

  def index
    @registered_applications = RegisteredApplication.all
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
    authorize @registered_application
  end

  def new
    @registered_application = RegisteredApplication.new
    authorize @registered_application
  end

  def create
    @registered_application = RegisteredApplication.new( registered_application_params.merge( user_id: current_user.id ) )
    authorize @registered_application

    if @registered_application.save
      redirect_to @registered_application, notice: "Application was registered successfully."
    else
      flash[:error] = "Error registering application. Please try again."
      render :new
    end
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
    authorize @registered_application
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])
    authorize @registered_application

    if @registered_application.update_attributes( registered_application_params )
      redirect_to @registered_application, notice: "Application updated successfully."
    else
      flash[:error] = "Error updating applcation. Please try again."
      render :edit
    end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])
    name = @registered_application.name
    authorize @registered_application

    if @registered_application.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
    else
      flash[:error] = "Error deleting application. Please try again."
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

private

  def registered_application_params
    params.require(:registered_application).permit(:name, :url, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @registered_applications = current_user.registered_applications
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end
end

app/helpers/events_controller_helper.rb
module EventsControllerHelper
end

app/views/events/edit.html.erb
<div class="page-header">
  <h1>Edit Application</h1>
</div>

<%= form_for @event do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url, "URL" %>
    <%= f.text_field :url %>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/events/new.html.erb
<div class="page-header">
  <h1>New Application</h1>
</div>

<%= form_for @event do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url, "URL" %>
    <%= f.text_field :url %>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "Apps", registered_applications_path %></li>
        <div class="pull-right user-info">
          <% if current_user %>
            Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>
      </ul>
      
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

  <%= yield %>
  </div>

</body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for [@registered_application] do |f| %>
  <% if @registered_application.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(@registered_application.errors.count, "error") %>.</h4>
      <ul>
        <% @registered_application.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(@registered_application.errors[:name]) do %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
  <% end %>
  <%= form_group_tag(@registered_application.errors[:description]) do %>
    <%= f.label :url %>
    <%= f.text_area :url, rows: 1, class: 'form-control', placeholder: "Enter URL" %>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/registered_applications/_registered_application.html.erb
<%= content_tag_for :div, registered_application, class: "row" do %>
  <div>
    <h3>
      <%= link_to "#{registered_application.name}", registered_application, class:'button-space' %>
      <% if policy(registered_application).destroy? %>
        <%= link_to "Delete", registered_application, method: :delete, remote: true, class: 'btn btn-xs btn-danger'%>
      <% end %>
    </h3>
  </div> 
<% end %>

app/views/registered_applications/destroy.js.erb
<% if @registered_application.destroyed? %>
  $(<%= dom_id( @registered_application ) %>).fadeOut(900);
<% else %>
  $(<%= dom_id( @registered_application ) %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>

app/views/registered_applications/edit.html.erb
<div class="page-header">
  <h1>Edit Application</h1>
</div>

<%= form_for @registered_application do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :url, "URL" %>
    <%= f.text_field :url %>
  </div>
  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/registered_applications/index.html.erb
<div align="center">
  <h1>All Applications</h1>
</div>
<div align="right">
  <%= link_to "New Application", new_registered_application_path, class: 'btn btn-success' %>
</div>

<%= render @registered_applications %>

app/views/registered_applications/new.html.erb
<div class="page-header">
  <h1>New Application</h1>
</div>

<%= render partial: 'form', locals: { registerd_application: @registered_application } %>

app/views/registered_applications/show.html.erb
<%= content_tag_for :div, @registered_application do %>
  <div align="center">
    <h1>
      <%= "#{@registered_application.name}" %>
      <br/><%= link_to @registered_application.url, "http://#{@registered_application.url}", :target => '_blank' %>
    </h1>
      <% if policy(@registered_application).edit? %>
        <%= link_to "Edit", edit_registered_application_path, class: 'btn btn-success' %>
        <%= link_to "Delete", registered_application_path(@registered_application), method: :delete, remote: true, class: 'btn btn-danger' %>
      <% end %>
  </div>
  <h1> Events </h1>
  <% @events.group_by(&:name).each do |name, events| %>
    <div>
      <%= name %> <span class="badge"><%= events.count %></span>
    </div>
  <% end %>
</br>
  <div>
    <button class="btn btn-primary" type="button">
    Total Events <span class="badge"><%= @events.count %></span>
    </button>
      <%= pie_chart @registered_application.events.group(:name).count %>
      <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
  </div>
<% end %>

app/views/users/_registered_application.html.erb
<%= content_tag_for :div, registered_application, class: "row" do %>
  <div>
    <h3>
      <%= link_to "#{registered_application.name}", registered_application, class:'button-space' %>
      <% if policy(registered_application).destroy? %>
        <%= link_to "Delete", registered_application, method: :delete, remote: true, class: 'btn btn-xs btn-danger'%>
      <% end %>
    </h3>
  </div> 

<% end %>

app/views/users/show.html.erb
<h1 class="text-center">My Registered Applications</h1>
  <% @registered_applications.each do | registered_application | %>
    <%= render partial: 'users/registered_application', locals: { registered_application: registered_application } %>
  <% end %>

app/views/welcome/index.html.erb
<h1>Welcome to Blocmetrics</h1>
<p>Blocmetrics is an analytics tool for tracking events on websites. Integrate with web apps to track user activity and report results.</p>

<br/>
<div id="footer">
  <h5>created by: Julia Park</h5>
</div>